hash-format = "sha256"

[[files]]
file = "config/openloader/data/irisfofs-iris-emojiful-datapack.zip"
hash = "96db21d55efe852e0f5959eb47f180573f9a6253a7c1c06bfcecec6cacf15a89"

[[files]]
file = "config/openloader/data/irisfofs-useful-emojiful-datapack.zip"
hash = "586a799a2263730e7f89b654dd1f72629bb2cfb38b8878d0681d60d301325b1f"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
hash = "4f20967ee66eb96cbcfaa63bea9d3424ac45b7db414c9a491f31c86012f34fb5"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "be28a9ff89c60140b2983eb91089e77bec90bc5a0379c25472be01cb14dcbb97"
metafile = true

[[files]]
file = "mods/better-modlist.pw.toml"
hash = "5ebc1849da4c78f57b8f4cde4320d5409ea9244e372d50afc6362ee88d66dd50"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "cc2e6dda94a7a6f5487843cafe569d8044bf9482cbf03f062cf4595f1fb05281"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "e1f1588b18947699ddc9b4f7c5b5406c5559155b8cb52dcd0f203c07c31cd0b8"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "f33a4720ef4f315b6d1f778039e9f7bdb8f5ef1b58a57d565c30fd1d8adee207"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "6cd235030774b3cfab54145cf616ab47b0afa57cacab75ede94c2682c9450ce9"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
hash = "683dbecfc509287f8a28fe2a73f180e5a488b9751c61a5a297c581287c5a57da"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "8fde54624913d86f1176cd1086fa485f1a872573dac144347c57cab76596b715"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8629fe0739a2243641a1a00b103682bcb2741a9295f9eac4c2a2135a867f8442"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "934d5afe2c8d68e991a5e24955c35abde9511a466ab62b34485363ad3f4dc43b"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "c27af69a7c64206beff3e59c671934d4eb9a3dc65fd589609c5e6f6bb60421bb"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "3f8fb0012b658c3ed2dfcde1385aa6255ee46cd18b77975d68665aaf0ee2a94d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "975f1280c712d2e86dd4ecddf89c516afbf3f1fb684499d3e5c71fc666c4888c"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "ff029ee6fc50f2696e96cdbcc696f42e75b483c9d7b83f2b1447dcf5c865e664"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "bbf03bec2bd4927ace16eef106c45b0f3ec53c48d5f43119520123ad98f3fdf1"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
hash = "0b921f73d5b1ad6615740956567d6cb06950f5520f094dbb7a045bb4bd5ba309"
metafile = true

[[files]]
file = "mods/emi-professions-(emip).pw.toml"
hash = "0477d572817d9de3a5569109a8d07a2e519af9ccf0e8236cae621369afbc6e4c"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
hash = "b53c40130b7c2f91237cf62480877414296fbea3525f2c824351c0c07f136ddb"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
hash = "08196e1229f323cc1eaf5969b93111705e8302a02d2acf134956f735f69e02c4"
metafile = true

[[files]]
file = "mods/enderpearl-backport.pw.toml"
hash = "58413c553a40461ed11843ef58f625fa57d129dc9ae04209528e190c561c677c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3443f52ef7c1f80ae1cedf459b23c38ac78dbe547cf2cc047e62d0cb2331c808"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
hash = "cd77d7f479a925f2c5147a9e4103a7c35c19292bf3a3144a59ecbb2905ceba62"
metafile = true

[[files]]
file = "mods/exposure-expanded.pw.toml"
hash = "5fad4cbcd06f11b18d1afd159d7b9cc320ed892103461d0d8206ee8ad2f1fcce"
metafile = true

[[files]]
file = "mods/exposure-knowlogy.pw.toml"
hash = "e62c113b0ad080336a32472500e65649dbb30b962ed31200e91e9454b0eaa18e"
metafile = true

[[files]]
file = "mods/exposure-polaroid.pw.toml"
hash = "87908da171a79c74062db88cd9f2a7283ab52eec1cf4194af415d34105c5ef9a"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "c22010071589a36869a478fda1eae893adcc15fc9ab9996a195cc6f54333891b"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
hash = "5916832d06322a7a54d87e1fe47da5009daed0213510573d9c311c5ceefa9937"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
hash = "574e4be5a4194cf6a44a5d064e3734dfbaac911c3caebfdf722ed7c35ff5215e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/flw-vanillin.pw.toml"
hash = "cbcaf4a18e45757f17d4a4f36469f879ae024a9fe58b8129d8a42d0faaeada22"
metafile = true

[[files]]
file = "mods/food-effect-tooltips-forge.pw.toml"
hash = "a71713076503c473ca3216c71285b2641ca250f80933d713a9f42edd03f5da17"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "ec1bd5b80399287ca33a113086bee9d5697b7e673c9f593e5a1aeca4c9bad4c9"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "184c6768f11e0c33c22c104397ad559c5b9337c709d1d05c8e9c93891dcddaee"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "35e72c6577b301ac850a959bce08ca1c8a68e58f7819191a61d20c7af536ee5d"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "11c4ac6932c14f3ad5a2c63d7f39eee1e9a2a91ffc079d5bd917c9aa381abdfb"
metafile = true

[[files]]
file = "mods/gnetum.pw.toml"
hash = "fe0bd7932e6989adcdbec64876a9d9d1dc9483cd0e44034c23e431e163f50492"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "019fea93516a470bbcad284dd0cbad6f4e2914d96221c86e3f87c12fe6321e10"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "9163b758163681f75e2048c798be880c50392684b127d7d87f42ea588deceb62"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "4a7571595a93220215375cf9fdb50969ad5c3a65010cfbff9088e200843ef8e6"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
hash = "2814d0d33ca5a6b95da1084b954eca9ca627890455c788811351ad6069a8f3bf"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "caa948011054593b7452cfc4fa7276ff61748770285fd6b7ee5078816eed043b"
metafile = true

[[files]]
file = "mods/knowlogy.pw.toml"
hash = "5519ac418243f4157d73056955a9d7cac7c22ad80c0881d7ce5d147a5565af26"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/lavender.pw.toml"
hash = "7dc27df21d8bd6b4e5387592063817c7de24a7e3ce8c90bb6bf3a9e22199d5e5"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "3f907a8532b4ca98390055ca0cb1bbd87e8ebcd44be6afe9b69280859ff37035"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "f8edc1d5fadb1b65f8f869893ec637ec8a5e5f92fb0a7f140e9e62977668f895"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "eae3c14c915400de36bf547550f630de727bbf48ae0ce719b99b2ff50ceaab0d"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "91696791780719730cb8826de0c53d8513a7c2b320f7d641dbeb6ca974e5cec3"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "abfc8909de1c851ccf4ef296e05d1017332a21fef76fd1f938828fcff925115b"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "d424a9260ef51bc102e56f0423d91dfabb739ccca8a86eb1c450ea631b739280"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
hash = "904c4adb3f8087a2c5381efd5d210183484934540372a5c839ab4790325e5cff"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "46831c04077a06df823bcd0f254833a90a9a9ccc78f5069f4b4c27fa301ac0cf"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "573f309a1bd1c410d149b6830aeddee7313e0698ac249a94f63a7e95c0eb146e"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "ce6e210ac63b92f3255c4896d116f35b0af8c57a1f84dab744d939535ea528ce"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c99c5bac469e8d6ece5aae80f08635e3bbb8367f0c586b6288573c725faefe69"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
hash = "fe85eb7e13d32999eb376d154be220d82134c534a3f066fa263fb4af11535232"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "b78044fd79ce21750d05dc61b6aede33c4b87cdc16a26f5aff472d4f73ab623c"
metafile = true

[[files]]
file = "mods/simple-snowy-fix-(forge-fabric).pw.toml"
hash = "42e83bf25ba1496791848df019cdbc6f71b7fe133e5e8a61d6ccc5c8f7aeb722"
metafile = true

[[files]]
file = "mods/smithing-template-viewer.pw.toml"
hash = "382d046069eefe23726209ccc23ef5916b0ce9fb4650a5256d4cd516f74d0790"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
hash = "a1deef8071fb83a13df63c289576813b82f0687eebda9b48b7667620d5d45103"
metafile = true

[[files]]
file = "mods/snow-sniffer.pw.toml"
hash = "87540c0d6ab0668d93a31b77eb794c76acee411475365a148eb1225e029d5a0d"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
hash = "514dab7fee713bccf17296d21b4f25d9e67954a96e7de1a8b586b90ea00a2bed"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "02b29315d2ec0d055d0ebba1f36879da5bcacc823328a668c7e7340fb2cb03d4"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "258a77de0a6db4c9ab045cbb240bcf4eac0dbbca3f6bc981fb461e55c247f23f"
metafile = true

[[files]]
file = "mods/structure-compass.pw.toml"
hash = "4338ec3c94e52d34a0678bbc124816bcb52b048dbe5bb75bab61ae1077d298e8"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "8ad02530347f7b0dfe84b8eb081e2eaa23cae536de0d289137902f7557fb3a33"
metafile = true

[[files]]
file = "mods/terralith-biome-saplings.pw.toml"
hash = "61d849b5dd59f7f9ccf950bbce846363c89dacd6a68af977c7cfa2f29c0ef8a6"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/torchmaster.pw.toml"
hash = "23ea2c32834281723c63d45ffe42969172492d36309755a46bc47154c3014b3f"
metafile = true

[[files]]
file = "mods/vanilla-backport-terralith-bwg-compat.pw.toml"
hash = "b85d6a2e0c4fc0532f6b5f22c7f8f8f8c9d830281c6975e8f0f1cdea08cb3b47"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "b278c479cc1d50ffbcf27e3514bcdb0995471eb11e2335c54255edc459b3462e"
metafile = true

[[files]]
file = "mods/variants-cit.pw.toml"
hash = "0e3c849a49f2de82e4f8c03ffb379cfadb13ae34768a3e2ada5c718ae427cdf9"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9b8940ac83dde84cfc59860c6544a4b1194e635786c26bd47dc15eee79e63598"
metafile = true

[[files]]
file = "resourcepacks/Xalis-Enchanted-Books-1.21-Variants-CIT.zip"
hash = "592cae3c3e28eb59a6991c492a12eca91e553585899e9fccff8729758fec3343"

[[files]]
file = "resourcepacks/Xalis-Potions-1.21-Variants-CIT.zip"
hash = "0ea313a91009fc8f75ba7b1f908b400f3ad8b5caf21b7a74ee91fea7904b5688"

[[files]]
file = "resourcepacks/mt-ct-d.pw.toml"
hash = "f52bcfb58f9988ad6abbcd25b770ec5e82669ccfd7aa80072c3e42ec2f9c458b"
metafile = true

[[files]]
file = "resourcepacks/sparkles.pw.toml"
hash = "f6cc6c6e40289a4a53254d81261d9a3865ba383c2576fe259d5fd23ca1c660f5"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
