hash-format = "sha256"

[[files]]
file = "README.md"

[[files]]
file = "config/almostunified/duplicates.json"

[[files]]
file = "config/almostunified/tags.json"

[[files]]
file = "config/almostunified/unification/materials.json"

[[files]]
file = "config/carryon-common.toml"

[[files]]
file = "config/clayworks-common.toml"

[[files]]
file = "config/create-common.toml"

[[files]]
file = "config/defaultoptions/keybindings.txt"

[[files]]
file = "config/defaultoptions/options.txt"

[[files]]
file = "config/defaultoptions/servers.dat"

[[files]]
file = "config/functionalstorage/functionalstorage-common.toml"

[[files]]
file = "config/jade/jade.json"

[[files]]
file = "config/jei-server.toml"

[[files]]
file = "config/openloader/packs/fofstography-tweaks/data/veinmining/enchantment/vein_mining.json"

[[files]]
file = "config/openloader/packs/fofstography-tweaks/pack.mcmeta"

[[files]]
file = "config/openloader/packs/hauser_legendary_tooltips/assets/legendarytooltips/frame_definitions.json"

[[files]]
file = "config/openloader/packs/hauser_legendary_tooltips/assets/legendarytooltips/textures/gui/tooltip_borders.png"

[[files]]
file = "config/openloader/packs/hauser_legendary_tooltips/pack.mcmeta"

[[files]]
file = "config/openloader/packs/hauser_legendary_tooltips/pack.png"

[[files]]
file = "config/openloader/packs/irisfofs-iris-emojiful-datapack.zip"

[[files]]
file = "config/openloader/packs/irisfofs-useful-emojiful-datapack.zip"

[[files]]
file = "config/openloader/packs/more mob heads v2.17.3 (MC 1.21-1.21.10).zip"

[[files]]
file = "config/openloader/packs/player head drops v1.1.14 (MC 1.21-1.21.10).zip"

[[files]]
file = "config/refinedstorage_quartz_arsenal-common.toml"

[[files]]
file = "config/tectonic.json"

[[files]]
file = "config/veinmining-server.toml"

[[files]]
file = "config/xaerominimap-common.txt"

[[files]]
file = "config/xaeroworldmap-common.txt"

[[files]]
file = "configureddefaults/README.md"

[[files]]
file = "configureddefaults/config/iris.properties"

[[files]]
file = "configureddefaults/config/pingwheel.json"

[[files]]
file = "configureddefaults/config/sodiumextras-client.toml"

[[files]]
file = "configureddefaults/config/supplementaries-client.toml"

[[files]]
file = "configureddefaults/config/veinmining-client.toml"

[[files]]
file = "configureddefaults/config/xaerominimap.txt"

[[files]]
file = "configureddefaults/config/xaeroworldmap.txt"

[[files]]
file = "kubejs/README.txt"

[[files]]
file = "kubejs/assets/emi/index/stacks/dyed_refined_storage_blocks.json"

[[files]]
file = "kubejs/assets/kubejs/models/block/trophy.json"

[[files]]
file = "kubejs/assets/kubejs/textures/block/example_block.png"

[[files]]
file = "kubejs/assets/kubejs/textures/block/trophy.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/elder_guardian_slab.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/example_item.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/incomplete_elder_guardian_slab.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/incomplete_raw_processor.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/processor_binding.png"

[[files]]
file = "kubejs/assets/kubejs/textures/item/soulless_elder_guardian_slab.png"

[[files]]
file = "kubejs/client_scripts/example.js"

[[files]]
file = "kubejs/client_scripts/jsconfig.json"

[[files]]
file = "kubejs/config/client.properties"

[[files]]
file = "kubejs/config/common.properties"

[[files]]
file = "kubejs/config/probe-settings.json"

[[files]]
file = "kubejs/server_scripts/jsconfig.json"

[[files]]
file = "kubejs/server_scripts/src/create_recipes_for_refined_storage.js"

[[files]]
file = "kubejs/server_scripts/src/exposure_stack_export.js"

[[files]]
file = "kubejs/server_scripts/src/fix_soymilk_for_other_mods.js"

[[files]]
file = "kubejs/server_scripts/src/fofs_tweaks.js"

[[files]]
file = "kubejs/server_scripts/src/hide_refined_storage_dyeing.js"

[[files]]
file = "kubejs/server_scripts/src/kanga_recipes.js"

[[files]]
file = "kubejs/server_scripts/src/mix_salt.js"

[[files]]
file = "kubejs/server_scripts/src/remove_op_recipes.js"

[[files]]
file = "kubejs/server_scripts/src/renewable_dirt.js"

[[files]]
file = "kubejs/server_scripts/src/stuffed_pumpkins_with_rice.js"

[[files]]
file = "kubejs/server_scripts/src/superheat_netherite.js"

[[files]]
file = "kubejs/startup_scripts/example.js"

[[files]]
file = "kubejs/startup_scripts/jsconfig.json"

[[files]]
file = "kubejs/startup_scripts/src/hauser.js"

[[files]]
file = "mods/abnormals-delight.pw.toml"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/almost-unified.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/asyncparticles.pw.toml"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/better-modlist.pw.toml"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/building-gadgets.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/chalk-mod.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chefs-delight.pw.toml"
metafile = true

[[files]]
file = "mods/clayworks.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
metafile = true

[[files]]
file = "mods/companion.pw.toml"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
metafile = true

[[files]]
file = "mods/create-food.pw.toml"
metafile = true

[[files]]
file = "mods/create-smart-bounds.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/create_oxidized.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/createbetterfps.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
metafile = true

[[files]]
file = "mods/cultural-delights.pw.toml"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/distraction-free-recipes.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/easel-does-it.pw.toml"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi-professions-(emip).pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emojiful.pw.toml"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/enderpearl-backport.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
metafile = true

[[files]]
file = "mods/exposure-expanded.pw.toml"
metafile = true

[[files]]
file = "mods/exposure-knowlogy.pw.toml"
metafile = true

[[files]]
file = "mods/exposure-polaroid.pw.toml"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/fast-async-world-save-forge-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/flw-vanillin.pw.toml"
metafile = true

[[files]]
file = "mods/food-effect-tooltips-forge.pw.toml"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
metafile = true

[[files]]
file = "mods/functional-storage.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/gnetum.pw.toml"
metafile = true

[[files]]
file = "mods/hide-experimental-warning.pw.toml"
metafile = true

[[files]]
file = "mods/horseman.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/justenoughbreeding.pw.toml"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/knowlogy.pw.toml"
metafile = true

[[files]]
file = "mods/kobolds.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/krypton-fnp.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs-create.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lavender.pw.toml"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/login-protection.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/more-delight.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/neapolitan.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/observable.pw.toml"
metafile = true

[[files]]
file = "mods/oceans-delight.pw.toml"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
metafile = true

[[files]]
file = "mods/picohud.pw.toml"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/recipe-essentials-forge-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/recipe-modification.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage-curios-integration.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage-emi-integration.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage-quartz-arsenal.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
metafile = true

[[files]]
file = "mods/simple-magnets.pw.toml"
metafile = true

[[files]]
file = "mods/simple-snowy-fix-(forge-fabric).pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/smithing-template-viewer.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
metafile = true

[[files]]
file = "mods/snow-sniffer.pw.toml"
metafile = true

[[files]]
file = "mods/snow-under-trees.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
metafile = true

[[files]]
file = "mods/sort-it-out.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/stdrdc.pw.toml"
metafile = true

[[files]]
file = "mods/structure-essentials-forge-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/terralith-biome-saplings.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
metafile = true

[[files]]
file = "mods/toastbegone.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage-knowlogy.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
metafile = true

[[files]]
file = "mods/torchmaster.pw.toml"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
metafile = true

[[files]]
file = "mods/universal-sawmill.pw.toml"
metafile = true

[[files]]
file = "mods/untitled-duck-mod.pw.toml"
metafile = true

[[files]]
file = "mods/vanilla-backport-terralith-bwg-compat.pw.toml"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
metafile = true

[[files]]
file = "mods/variants-cit.pw.toml"
metafile = true

[[files]]
file = "mods/vegan-delight.pw.toml"
metafile = true

[[files]]
file = "mods/vein-mining.pw.toml"
metafile = true

[[files]]
file = "mods/vulpine.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/Create Style for Refined Storage.zip"

[[files]]
file = "resourcepacks/Xalis-Enchanted-Books-1.21-Variants-CIT.zip"

[[files]]
file = "resourcepacks/Xalis-Potions-1.21-Variants-CIT.zip"

[[files]]
file = "resourcepacks/building-gadgets-create-like.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/mt-ct-d.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/sparkles.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/varied-foxes-1-2 iris v1.1.zip"

[[files]]
file = "shaderpacks/CR5.6.1 + EP1.7.8 fofs.txt"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1 + EuphoriaPatches_1.7.8.txt"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
metafile = true
