name = "Fofstography 2025"
author = "irisfofs"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "565b6e11543b00880ab88f43cfebda2ba62a9029d9f52338b4b9c40939b2dddb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
