name = "Fofstography 2025"
author = "irisfofs"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fccd19fd1c923fb0ea47a2edb284055f43ff11b8ec11b1bbac1715d42f68380"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
