[wirelessCraftingGrid]
  # Default: 1000
  # Range: 0 ~ 9223372036854775807
  energyCapacity = 64000
  # Default: 5
  # Range: 0 ~ 9223372036854775807
  openEnergyUsage = 30
  # Default: 5
  # Range: 0 ~ 9223372036854775807
  craftingEnergyUsage = 10
  # Default: 10
  # Range: 0 ~ 9223372036854775807
  autocraftingEnergyUsage = 50
  # Default: 5
  # Range: 0 ~ 9223372036854775807
  clearMatrixEnergyUsage = 25
  # Default: 5
  # Range: 0 ~ 9223372036854775807
  recipeTransferEnergyUsage = 25
